<?php

use Illuminate\Database\Seeder;
use App\Box_Presentation;
class Box_PresentationTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Box_Presentation::create([
            'Id_Bo'=>1,
            'Id_Pre'=>1,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>1,
            'Id_Pre'=>2,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>1,
            'Id_Pre'=>3,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>2,
            'Id_Pre'=>1,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>2,
            'Id_Pre'=>2,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>2,
            'Id_Pre'=>3,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>3,
            'Id_Pre'=>1,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>3,
            'Id_Pre'=>2,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>3,
            'Id_Pre'=>3,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>4,
            'Id_Pre'=>1,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>4,
            'Id_Pre'=>2,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>4,
            'Id_Pre'=>3,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>5,
            'Id_Pre'=>1,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>5,
            'Id_Pre'=>2,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>5,
            'Id_Pre'=>3,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>6,
            'Id_Pre'=>1,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>6,
            'Id_Pre'=>2,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>6,
            'Id_Pre'=>3,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>7,
            'Id_Pre'=>1,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>7,
            'Id_Pre'=>2,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>7,
            'Id_Pre'=>3,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>8,
            'Id_Pre'=>1,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>8,
            'Id_Pre'=>2,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>8,
            'Id_Pre'=>3,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>9,
            'Id_Pre'=>1,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>9,
            'Id_Pre'=>2,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>9,
            'Id_Pre'=>3,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>10,
            'Id_Pre'=>1,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>10,
            'Id_Pre'=>2,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>10,
            'Id_Pre'=>3,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>11,
            'Id_Pre'=>1,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>11,
            'Id_Pre'=>2,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>11,
            'Id_Pre'=>3,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>12,
            'Id_Pre'=>1,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>12,
            'Id_Pre'=>2,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>12,
            'Id_Pre'=>3,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>13,
            'Id_Pre'=>1,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>13,
            'Id_Pre'=>2,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>13,
            'Id_Pre'=>3,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>14,
            'Id_Pre'=>1,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>14,
            'Id_Pre'=>2,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>14,
            'Id_Pre'=>3,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>15,
            'Id_Pre'=>1,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>15,
            'Id_Pre'=>2,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>15,
            'Id_Pre'=>3,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>16,
            'Id_Pre'=>1,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>16,
            'Id_Pre'=>2,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>16,
            'Id_Pre'=>3,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>17,
            'Id_Pre'=>1,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>17,
            'Id_Pre'=>2,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>17,
            'Id_Pre'=>3,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>18,
            'Id_Pre'=>1,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>18,
            'Id_Pre'=>2,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>18,
            'Id_Pre'=>3,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>19,
            'Id_Pre'=>1,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>19,
            'Id_Pre'=>2,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>19,
            'Id_Pre'=>3,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>20,
            'Id_Pre'=>1,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>20,
            'Id_Pre'=>2,
            'Id_Est'=>3,
        ]);
        Box_Presentation::create([
            'Id_Bo'=>20,
            'Id_Pre'=>3,
            'Id_Est'=>3,
        ]);
    }
}
