<?php

use Illuminate\Database\Seeder;
use App\Box;
class BoxTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Box::create([
            'Cod_Bo'=>'L1',
            'Price'=>600,
            'Id_Est'=>1,
        ]);
        Box::create([
            'Cod_Bo'=>'L2',
            'Price'=>600,
            'Id_Est'=>1,
        ]);
        Box::create([
            'Cod_Bo'=>'L3',
            'Price'=>600,
            'Id_Est'=>1,
        ]);
        Box::create([
            'Cod_Bo'=>'L4',
            'Price'=>600,
            'Id_Est'=>1,
        ]);
        Box::create([
            'Cod_Bo'=>'K1',
            'Price'=>600,
            'Id_Est'=>1,
        ]);
        Box::create([
            'Cod_Bo'=>'K4',
            'Price'=>600,
            'Id_Est'=>1,
        ]);
        Box::create([
            'Cod_Bo'=>'J2',
            'Price'=>600,
            'Id_Est'=>1,
        ]);
        Box::create([
            'Cod_Bo'=>'J3',
            'Price'=>600,
            'Id_Est'=>1,
        ]);
        Box::create([
            'Cod_Bo'=>'A1',
            'Price'=>500,
            'Id_Est'=>1,
        ]);
        Box::create([
            'Cod_Bo'=>'A2',
            'Price'=>500,
            'Id_Est'=>1,
        ]);
        Box::create([
            'Cod_Bo'=>'A3',
            'Price'=>500,
            'Id_Est'=>1,
        ]);
        Box::create([
            'Cod_Bo'=>'T2',
            'Price'=>400,
            'Id_Est'=>1,
        ]);
        Box::create([
            'Cod_Bo'=>'T3',
            'Price'=>400,
            'Id_Est'=>1,
        ]);
        Box::create([
            'Cod_Bo'=>'T4',
            'Price'=>400,
            'Id_Est'=>1,
        ]);
        Box::create([
            'Cod_Bo'=>'S1',
            'Price'=>400,
            'Id_Est'=>1,
        ]);
        Box::create([
            'Cod_Bo'=>'S4',
            'Price'=>400,
            'Id_Est'=>1,
        ]);
        Box::create([
            'Cod_Bo'=>'R1',
            'Price'=>400,
            'Id_Est'=>1,
        ]);
        Box::create([
            'Cod_Bo'=>'R2',
            'Price'=>400,
            'Id_Est'=>1,
        ]);
        Box::create([
            'Cod_Bo'=>'R3',
            'Price'=>400,
            'Id_Est'=>1,
        ]);

        Box::create([
            'Cod_Bo'=>'R4',
            'Price'=>400,
            'Id_Est'=>1,
        ]);
    }
}
